# Generated by Django 5.0.4 on 2024-05-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_activity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='Not completed', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PM_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_name', models.CharField(max_length=255)),
                ('translator', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('remaining_text_volume', models.CharField(default='0%', max_length=100)),
                ('status', models.CharField(default='Not Completed', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.pm_project')),
            ],
        ),
    ]
