# Generated by Django 3.2.9 on 2024-05-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pm_activity_task_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_project',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.pm_activity'),
            preserve_default=False,
        ),
    ]
