# Generated by Django 5.0.4 on 2024-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_selected_translator_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected_translator',
        ),
    ]
